#!/usr/bin/env python3
"""
research.py – Research-Aufgaben erstellen und verwalten.

Usage:
    research                          # Interaktiv: Menü mit Aktionen
    research list                     # Zeigt offene Requests aus _Requests.md
    research run "UE5 Nanite"         # Erstellt eine neue Research-Aufgabe
    research run "KI Agenten" --topic "AI"  # Mit Kategorie
"""

import sys
import argparse
from datetime import date
from pathlib import Path

VAULT_ROOT = Path(__file__).resolve().parent.parent.parent
INBOX = VAULT_ROOT / "Research" / "_Inbox"
REQUESTS_FILE = VAULT_ROOT / "Research" / "_Requests.md"

TOPICS = {
    "ue5": "UE5-Tech",
    "nanite": "UE5-Tech",
    "lumen": "UE5-Tech",
    "unreal": "UE5-Tech",
    "game": "Game-Design",
    "design": "Game-Design",
    "combat": "Game-Design",
    "level": "Game-Design",
    "linux": "Linux-Tools",
    "disk": "Linux-Tools",
    "arch": "Linux-Tools",
    "web": "Web-Dev",
    "react": "Web-Dev",
    "typescript": "Web-Dev",
    "tauri": "Web-Dev",
    "svelte": "Web-Dev",
    "vue": "Web-Dev",
    "python": "Programming",
    "rust": "Programming",
    "blender": "3D-Art",
    "godot": "Game-Dev",
    "ai": "AI / ML",
    "agent": "AI / ML",
    "llm": "AI / ML",
}


def guess_topic(query: str) -> str:
    """Erkennt die Kategorie aus dem Suchbegriff."""
    query_lower = query.lower()
    for keyword, topic in TOPICS.items():
        if keyword in query_lower:
            return topic
    return "Unsortiert"


def list_requests():
    """Zeigt den Inhalt der _Requests.md an."""
    if not REQUESTS_FILE.exists():
        print("📭  Keine _Requests.md gefunden.")
        print(f"   Erstelle unter: {REQUESTS_FILE}")
        REQUESTS_FILE.write_text("# Research Requests\n\nOffene Forschungsthemen:\n\n- [ ] Beispiel: UE5 Nanite Performance\n")
        print("   → Leere Vorlage angelegt.")
        return

    text = REQUESTS_FILE.read_text()
    print()
    print("  📋  Offene Research-Requests")
    print("  " + "─" * 40)
    print()
    for line in text.splitlines():
        if line.strip().startswith("- [ ]"):
            print(f"     {line.strip()}")
    print()
    print(f"  📄  {REQUESTS_FILE}")
    print()


def create_research_task(topic: str, category: str = None):
    """Erstellt eine neue Research-Datei in _Inbox."""
    if not INBOX.exists():
        INBOX.mkdir(parents=True)

    today = date.today().isoformat()
    safe_name = topic.lower().strip().replace(" ", "-").replace("/", "-")
    safe_name = "".join(c for c in safe_name if c.isalnum() or c in "-_")
    filename = f"{today}_{safe_name}.md"
    filepath = INBOX / filename

    if filepath.exists():
        print(f"⚠️  Datei existiert bereits: {filepath}")
        return

    if category is None:
        category = guess_topic(topic)

    content = f"""---
title: "Research: {topic}"
type: research
source: web
agent: hermes
date: {today}
status: inbox
tags: [research]
related_topics: [{category}]
---

# Research: {topic}

> Auto-generated by `research.py` · {today}

---

## Research Question

Was genau soll recherchiert werden?

---

## Expected Sources

- (Agent füllt aus)

---

## Notes

(Agent füllt aus)
"""
    filepath.write_text(content)
    print()
    print(f"  ✅  Research-Aufgabe erstellt")
    print(f"  " + "─" * 40)
    print(f"  📄  {filepath}")
    print(f"  🏷️   Thema:    {topic}")
    print(f"  📂  Kategorie: {category}")
    print(f"  💡  Nächster Schritt: Die Datei öffnen und die Research Question ausfüllen!")


def interactive_menu():
    """Interaktiver Modus: Menü anzeigen und Aktion auswählen."""
    print()
    print("  📚  Research-Assistent")
    print("  " + "─" * 40)
    print("  1)  Research-Aufgabe erstellen")
    print("  2)  Offene Requests anzeigen")
    print("  3)  Beenden")
    print()

    try:
        choice = input("  Auswahl [1-3]: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        return

    if choice == "1":
        topic = input("  Forschungsthema: ").strip()
        if topic:
            cat_input = input("  Kategorie (leer = automatisch): ").strip()
            create_research_task(topic, cat_input if cat_input else None)
        else:
            print("  ❌  Kein Thema eingegeben.")
    elif choice == "2":
        list_requests()
    else:
        print("  👋  Tschüss!")


def main():
    parser = argparse.ArgumentParser(
        description="📚 Erstellt Research-Aufgaben und zeigt offene Requests an.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Beispiele:
  research                          # Interaktives Menü
  research list                     # Offene Requests anzeigen
  research run "UE5 Nanite"         # Neue Research-Aufgabe
  research run "KI" --topic "AI"    # Mit eigener Kategorie
        """,
    )
    parser.add_argument("command", nargs="?", default=None,
                        choices=["list", "run"],
                        help="Aktion: list (Requests zeigen) oder run (Aufgabe erstellen)")
    parser.add_argument("topic", nargs="?", default=None,
                        help="Forschungsthema (für run)")
    parser.add_argument("--topic", "-t", dest="category", default=None,
                        help="Kategorie manuell setzen (z. B. 'UE5-Tech', 'Game-Design')")

    args = parser.parse_args()

    # Interaktiv: kein Command
    if args.command is None:
        interactive_menu()
        return

    # list
    if args.command == "list":
        list_requests()
        return

    # run
    if args.command == "run":
        if not args.topic:
            print("❌  Kein Thema angegeben.")
            print(f"   Usage: research run \"Thema\"")
            sys.exit(1)
        create_research_task(args.topic, args.category)
        return


if __name__ == "__main__":
    main()
