#!/usr/bin/env python3
"""
research.py  --  Research-Aufgaben erstellen und verwalten.

Usage:
    research                          # Interaktives Menue
    research list                     # Offene Requests anzeigen
    research run "UE5 Nanite"         # Neue Research-Aufgabe
"""

import sys
import argparse
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _shared.ui import header, section, ok, fail, info, tip, keyval, spacer, hr, prompt, list_items

VAULT_ROOT = Path(__file__).resolve().parent.parent.parent
INBOX = VAULT_ROOT / "Research" / "_Inbox"
REQUESTS_FILE = VAULT_ROOT / "Research" / "_Requests.md"

TOPICS = {
    "ue5": "UE5-Tech", "nanite": "UE5-Tech", "lumen": "UE5-Tech", "unreal": "UE5-Tech",
    "game": "Game-Design", "design": "Game-Design", "combat": "Game-Design",
    "linux": "Linux-Tools", "arch": "Linux-Tools", "disk": "Linux-Tools",
    "web": "Web-Dev", "react": "Web-Dev", "svelte": "Web-Dev", "vue": "Web-Dev",
    "tauri": "Web-Dev", "typescript": "Web-Dev",
    "python": "Programming", "rust": "Programming",
    "blender": "3D-Art", "godot": "Game-Dev",
    "ai": "AI / ML", "agent": "AI / ML", "llm": "AI / ML",
}


def guess_topic(query: str) -> str:
    q = query.lower()
    for kw, topic in TOPICS.items():
        if kw in q:
            return topic
    return "Unsortiert"


def list_requests():
    if not REQUESTS_FILE.exists():
        header("Research  -  No Requests")
        info("No _Requests.md found.")
        REQUESTS_FILE.write_text("# Research Requests\n\nOffene Forschungsthemen:\n\n- [ ] Beispiel: UE5 Nanite Performance\n")
        ok("Created empty template: _Requests.md")
        return

    text = REQUESTS_FILE.read_text()
    header("Research  -  Open Requests")
    count = 0
    for line in text.splitlines():
        if line.strip().startswith("- [ ]"):
            print(f"  {line.strip()}")
            count += 1
    spacer()
    info(f"{count} open request(s) in {REQUESTS_FILE}")


def create_task(topic: str, category: str = None):
    if not INBOX.exists():
        INBOX.mkdir(parents=True)

    today = date.today().isoformat()
    safe = topic.lower().strip().replace(" ", "-").replace("/", "-")
    safe = "".join(c for c in safe if c.isalnum() or c in "-_")
    filename = f"{today}_{safe}.md"
    filepath = INBOX / filename

    if filepath.exists():
        fail(f"Already exists: {filepath}")
        return

    cat = category or guess_topic(topic)

    content = f"""---
title: "Research: {topic}"
type: research
source: web
agent: hermes
date: {today}
status: inbox
tags: [research]
related_topics: [{cat}]
---

# Research: {topic}

> Auto-generated by `research.py` | {today}

---

## Research Question

Was genau soll recherchiert werden?

---

## Expected Sources

- (Agent fills out)

---

## Notes

(Agent fills out)
"""
    filepath.write_text(content)
    header("Research  -  Task Created")
    keyval("File", str(filepath))
    keyval("Topic", topic)
    keyval("Category", cat)
    spacer()
    tip("Open the file and fill in the Research Question.")


def interactive_menu():
    header("Research Assistant")
    print("  1)  Create research task")
    print("  2)  Show open requests")
    print("  q)  Quit")
    spacer()

    choice = prompt("Choice")
    if choice == "1":
        topic = prompt("Research topic")
        if not topic:
            return
        cat = prompt("Category (leave empty for auto-detect)")
        create_task(topic, cat if cat else None)
    elif choice == "2":
        list_requests()
    else:
        print("  Goodbye!")


def main():
    parser = argparse.ArgumentParser(description="Research task management")
    parser.add_argument("command", nargs="?", default=None, choices=["list", "run"],
                        help="Action: list | run")
    parser.add_argument("topic", nargs="?", default=None, help="Topic (for run)")
    parser.add_argument("--topic", "-t", dest="category", default=None,
                        help="Category override")
    args = parser.parse_args()

    if args.command is None:
        interactive_menu()
        return
    if args.command == "list":
        list_requests()
        return
    if args.command == "run":
        if not args.topic:
            fail("No topic specified.")
            print("   Usage: research run \"<topic>\"")
            sys.exit(1)
        create_task(args.topic, args.category)


if __name__ == "__main__":
    main()
