#!/usr/bin/env python3
"""
research-cron-orchestrator.py – Plant和研究-Aufträge aus _Requests.md und
startet Research-Cron-Jobs.

Usage:
    python3 _Meta/Scripts/research-cron-orchestrator.py list
    python3 _Meta/Scripts/research-cron-orchestrator.py run "UE5 Nanite"
    
Design:
- Liest Research/_Requests.md (wenn vorhanden) für offene Aufträge
- Kann manuell mit "run <topic>" aufgerufen werden
- Erstellt Research/_Inbox/<date>_<topic>.md mit Template
"""

import os
import sys
import json
from datetime import date
from pathlib import Path

VAULT_ROOT = Path(__file__).resolve().parent.parent.parent
INBOX = VAULT_ROOT / "Research" / "_Inbox"
REQUESTS_FILE = VAULT_ROOT / "Research" / "_Requests.md"

TOPICS = {
    "ue5": "UE5-Tech",
    "nanite": "UE5-Tech",
    "lumen": "UE5-Tech",
    "game-design": "Game-Design",
    "combat": "Game-Design",
    "linux": "Linux-Tools",
    "disk": "Linux-Tools",
    "web": "Web-Dev",
    "react": "Web-Dev",
    "typescript": "Web-Dev",
    "tauri": "Web-Dev",
}


def guess_topic(query: str) -> str:
    query_lower = query.lower()
    for keyword, topic in TOPICS.items():
        if keyword in query_lower:
            return topic
    return "Unsortiert"


def list_requests():
    if not REQUESTS_FILE.exists():
        print("📭 No _Requests.md found.")
        return
    text = REQUESTS_FILE.read_text()
    print(text)


def create_research_task(topic: str):
    today = date.today().isoformat()
    filename = f"{today}_{topic.lower().replace(' ', '-')}.md"
    filepath = INBOX / filename
    
    category = guess_topic(topic)
    
    content = f"""---
title: "Research: {topic}"
type: research
source: web
agent: hermes
date: {today}
status: inbox
tags: [research]
related_topics: [{category}]
---

# Research: {topic}

> Auto-generated by research-cron-orchestrator.py
> Date: {today}

## Research Question
Was genau soll recherchiert werden?

## Expected Sources
- (Agent füllt aus)

## Notes
(Agent füllt aus)
"""
    filepath.write_text(content)
    print(f"✅ Research task created: {filepath}")
    print(f"   Topic: {topic}")
    print(f"   Category: {category}")


def main():
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python3 research-cron-orchestrator.py list")
        print("  python3 research-cron-orchestrator.py run \"<topic>\"")
        sys.exit(1)

    command = sys.argv[1]
    if command == "list":
        list_requests()
    elif command == "run":
        if len(sys.argv) < 3:
            print("❌ Missing topic. Usage: run \"<topic>\"")
            sys.exit(1)
        topic = " ".join(sys.argv[2:])
        create_research_task(topic)
    else:
        print(f"Unknown command: {command}")
        sys.exit(1)


if __name__ == "__main__":
    main()
